### ISSUE TITLE
IR emitters in a quadrilateral?

### ISSUE THREAD

**Issue by arpruss** [Prow7/ir-light-gun#3]
Does the code work with the IR emitters arranged in a quadrilateral rather than a line? With a linear arrangement there is no way to reconstruct where the gun is pointing if one changes how high the gun is above the ground, unless one uses an accelerometer.

**Comment by Prow7** [comment]
Yes, the 4 IR emitters must be arranged in a rectangle (or square), not a line. My project is based on Samco's 4IR project. The README in the SamcoEnhanced sketch directory specifies this. https://github.com/Prow7/ir-light-gun/tree/main/SamcoEnhanced

**Comment by arpruss** [comment]
Nice!

BTW, have you thought of adding an accelerometer so that the gun can be pointed sideways and still work?

**Comment by Prow7** [comment]
No, but if someone else implements that feature I'll add it to the code.

I am closing this issue (since it's not really an issue). However, I just enabled the Discussions feature so feel free to ask more questions there.
