### ISSUE TITLE
I keep getting this error when trying to compile it for a raspberry pi pico. How do i fix this

### ISSUE THREAD

**Issue by K-Senthil-Shunmugam** [Prow7/ir-light-gun#5]
/home/senthil_kmp/.arduino15/packages/rp2040/tools/pqt-gcc/2.1.0-a-d3d2e6b/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld: /tmp/arduino/sketches/D229B1B296ABA5D9041CAFA915D8D146/libraries/Keyboard/Keyboard.cpp.o: in function `tud_hid_set_report_cb':
/home/senthil_kmp/.arduino15/packages/rp2040/hardware/rp2040/3.6.0/libraries/Keyboard/src/Keyboard.cpp:59: multiple definition of `tud_hid_set_report_cb'; /tmp/arduino/sketches/D229B1B296ABA5D9041CAFA915D8D146/libraries/Adafruit_TinyUSB_Library/arduino/hid/Adafruit_USBD_HID.cpp.o:/home/senthil_kmp/Arduino/libraries/Adafruit_TinyUSB_Library/src/arduino/hid/Adafruit_USBD_HID.cpp:243: first defined here
/home/senthil_kmp/.arduino15/packages/rp2040/tools/pqt-gcc/2.1.0-a-d3d2e6b/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld: /tmp/arduino/sketches/D229B1B296ABA5D9041CAFA915D8D146/libraries/Keyboard/Keyboard.cpp.o: in function `_ZN9Keyboard_18sendConsumerReportEt':
/home/senthil_kmp/.arduino15/packages/rp2040/hardware/rp2040/3.6.0/libraries/Keyboard/src/Keyboard.cpp:52: undefined reference to `_Z13__USBHIDReadyv'
/home/senthil_kmp/.arduino15/packages/rp2040/tools/pqt-gcc/2.1.0-a-d3d2e6b/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld: /tmp/arduino/sketches/D229B1B296ABA5D9041CAFA915D8D146/libraries/Keyboard/Keyboard.cpp.o: in function `_ZN9Keyboard_10sendReportEP9KeyReport':
/home/senthil_kmp/.arduino15/packages/rp2040/hardware/rp2040/3.6.0/libraries/Keyboard/src/Keyboard.cpp:43: undefined reference to `_Z13__USBHIDReadyv'

**Comment by Prow7** [comment]
Install the Pi Pico/RP2040 version 2.7.3 and the code should compile. Something broke starting with version 3 of the RP2040 board library and I haven't fixed it yet.

**Comment by K-Senthil-Shunmugam** [comment]
Thanks a lot that solved the error.
