### ISSUE TITLE
undefined reference to `_Z13__USBHIDReadyv' 

### ISSUE THREAD

**Issue by Mons1ter** [Prow7/ir-light-gun#6]
When compiling, it displays "C:\Users\admin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.6.0\libraries\Keyboard\src/Keyboard.cpp:43: undefined reference to `_Z13__USBHIDReadyv'", But the code ""_Z13__USBHIDReadyv" was not found in the source code.

It is error:
c:/users/admin/appdata/local/arduino15/packages/rp2040/tools/pqt-gcc/2.1.0-a-d3d2e6b/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld.exe: C:\Users\admin\AppData\Local\Temp\arduino\sketches\08CF636668B5462CB34EDB6061AA0222\libraries\Keyboard\Keyboard.cpp.o: in function `tud_hid_set_report_cb':
C:\Users\admin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.6.0\libraries\Keyboard\src/Keyboard.cpp:59: multiple definition of `tud_hid_set_report_cb'; C:\Users\admin\AppData\Local\Temp\arduino\sketches\08CF636668B5462CB34EDB6061AA0222\libraries\Adafruit_TinyUSB_Library\arduino\hid\Adafruit_USBD_HID.cpp.o:c:\Users\admin\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\arduino\hid/Adafruit_USBD_HID.cpp:243: first defined here
c:/users/admin/appdata/local/arduino15/packages/rp2040/tools/pqt-gcc/2.1.0-a-d3d2e6b/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld.exe: C:\Users\admin\AppData\Local\Temp\arduino\sketches\08CF636668B5462CB34EDB6061AA0222\libraries\Keyboard\Keyboard.cpp.o: in function `_ZN9Keyboard_18sendConsumerReportEt':
C:\Users\admin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.6.0\libraries\Keyboard\src/Keyboard.cpp:52: undefined reference to `_Z13__USBHIDReadyv'
c:/users/admin/appdata/local/arduino15/packages/rp2040/tools/pqt-gcc/2.1.0-a-d3d2e6b/bin/../lib/gcc/arm-none-eabi/12.3.0/../../../../arm-none-eabi/bin/ld.exe: C:\Users\admin\AppData\Local\Temp\arduino\sketches\08CF636668B5462CB34EDB6061AA0222\libraries\Keyboard\Keyboard.cpp.o: in function `_ZN9Keyboard_10sendReportEP9KeyReport':
C:\Users\admin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.6.0\libraries\Keyboard\src/Keyboard.cpp:43: undefined reference to `_Z13__USBHIDReadyv'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "Adafruit_TinyUSB.h"
  Used: C:\Users\admin\Documents\Arduino\libraries\Adafruit_TinyUSB_Library
  Not used: C:\Users\admin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.6.0\libraries\Adafruit_TinyUSB_Arduino
exit status 1

Compilation error: exit status 1

**Comment by Prow7** [comment]
Install the Pi Pico/RP2040 board version 2.7.3 and the code should compile. Something broke starting with version 3 of the RP2040 board library and I haven't fixed it yet.

**Comment by Prow7** [comment]
This issue is now officially fixed. The project builds with the latest Arduino-Pico version 3.9.0.
